spring:
  application:
    name: testing
  output:
    ansi:
      enabled: always
server:
  port: 8081
  error:
    include-exception: true
    include-message: always
    include-stacktrace: never
logging:
  level:
    com.example.testing: debug